import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import DataTable from 'datatables.net-react';
import DT from 'datatables.net-dt';
import 'datatables.net-dt/css/dataTables.dataTables.css';
import './App.css';
import DocumentForm from './DocumentForm';
import PaymentsView from './PaymentsView';
import MonthlyGenerator from './MonthlyGenerator';
DataTable.use(DT);
type Row=Record<string,string|number>; type Field={name:string;label:string;type?:string;required?:boolean}; type Config={base:string;id:string;fields:Field[]};
const api=import.meta.env.VITE_API_URL??'';
const modules=[['Resumen','resumen'],['Clientes','clientes'],['Proveedores','proveedores'],['Marcas','marcas'],['Productos','productos'],['Inventario','inventario'],['Compras','compras'],['Facturación','facturas'],['Consulta de pagos','pagos'],['Cartera pendiente','pendientes'],['Genera mensual','genera-mensual'],['Instalaciones','instalaciones'],['Mensualidades','mensualidades'],['Órdenes de trabajo','ordenes-trabajo']];
const configs:Record<string,Config>={clientes:{base:'api/clientes',id:'cedula',fields:[['cedula','Cédula/RUC'],['apellidos','Apellidos'],['nombres','Nombres'],['direccion','Dirección'],['telefono','Teléfono'],['email','Correo'],['observacion','Observación']].map(([name,label])=>({name,label,required:['cedula','apellidos','nombres','direccion'].includes(name),type:name==='email'?'email':undefined}))},proveedores:{base:'api/administracion/proveedores',id:'ciRuc',fields:[['ciRuc','Cédula/RUC'],['razonSocial','Razón social'],['apellidos','Apellidos'],['nombres','Nombres'],['direccion','Dirección'],['telefono','Teléfono'],['celular','Celular'],['email','Correo'],['formaPago','Forma de pago'],['observaciones','Observaciones']].map(([name,label])=>({name,label,required:!['telefono','celular','observaciones'].includes(name),type:name==='email'?'email':undefined}))},marcas:{base:'api/administracion/marcas',id:'mar_codigo',fields:[{name:'descripcion',label:'Descripción',required:true},{name:'modelo',label:'Modelo',required:true}]},productos:{base:'api/administracion/productos',id:'codigo',fields:[{name:'descripcion',label:'Descripción',required:true},{name:'marcaCodigo',label:'Código de marca',type:'number',required:true},{name:'modelo',label:'Modelo'},{name:'imei',label:'IMEI/serie'},{name:'precio',label:'Precio',type:'number',required:true},{name:'unidad',label:'Unidad',required:true},{name:'observacion',label:'Observación'}]}};
configs.instalaciones={base:'api/servicios/instalaciones',id:'codigo',fields:[{name:'clienteCedula',label:'Cédula/RUC del cliente',required:true},{name:'fechaInstalacion',label:'Fecha de instalación',type:'date',required:true},{name:'costoInstalacion',label:'Costo de instalación',type:'number',required:true},{name:'valorMensual',label:'Valor mensual',type:'number',required:true},{name:'descripcionAntena',label:'Descripción de antena'},{name:'ipAntenaWan',label:'IP antena WAN'},{name:'loginAntena',label:'Usuario antena'},{name:'passwordAntena',label:'Contraseña antena'},{name:'ipWanRouter',label:'IP WAN router'},{name:'loginRouter',label:'Usuario router'},{name:'passwordRouter',label:'Contraseña router'},{name:'passwordWifi',label:'Contraseña Wi-Fi'},{name:'ipAccessPoint',label:'IP access point'},{name:'observaciones',label:'Observaciones'}]};
configs.mensualidades={base:'api/servicios/mensualidades',id:'codigo',fields:[{name:'instalacionCodigo',label:'Código de instalación',type:'number',required:true},{name:'clienteCedula',label:'Cédula/RUC del cliente',required:true},{name:'desde',label:'Desde',type:'date',required:true},{name:'hasta',label:'Hasta',type:'date',required:true},{name:'cuota',label:'Cuota',type:'number',required:true}]};
export default function App(){const[active,setActive]=useState('resumen'),[data,setData]=useState<unknown>(null),[error,setError]=useState(''),[buscar,setBuscar]=useState(''),[usuario,setUsuario]=useState<string|null>(null),[checking,setChecking]=useState(true),[editing,setEditing]=useState<Row|null|undefined>(undefined);useEffect(()=>{fetch(`${api}/api/auth/sesion`,{credentials:'include'}).then(async r=>{if(r.ok)setUsuario((await r.json()).usuario)}).finally(()=>setChecking(false))},[]);async function request(path:string,options?:RequestInit){const r=await fetch(`${api}/${path}`,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options?.headers??{})}});if(r.status===401){setUsuario(null);throw new Error('La sesión terminó.')}if(!r.ok){const p=await r.json().catch(()=>null);throw new Error(p?.detail??p?.title??`Error ${r.status}`)}return r}async function load(){setError('');try{const path=active==='clientes'?`api/clientes?buscar=${encodeURIComponent(buscar)}`:active==='marcas'?'api/administracion/marcas':`api/modulos/${active}`;setData(await(await request(path)).json())}catch(e){setError(e instanceof Error?e.message:'Error de conexión')}}useEffect(()=>{setEditing(undefined);if(usuario)load()},[active,usuario]);async function remove(row:Row){const c=configs[active],id=row[c.id];if(!confirm('¿Desea anular este registro?'))return;try{await request(`${c.base}/${encodeURIComponent(String(id))}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo anular')}}if(checking)return <Center text="Verificando sesión…"/>;if(!usuario)return <Login onLogin={setUsuario}/>;const config=configs[active];return <div className="shell"><aside><div className="brand"><span>C</span><div>Comercial<small>Gestión integral</small></div></div><nav>{modules.map(([label,key])=><button className={active===key?'active':''} onClick={()=>setActive(key)} key={key}>{label}</button>)}</nav></aside><main><header><div><p className="eyebrow">SISTEMA COMERCIAL</p><h1>{modules.find(x=>x[1]===active)?.[0]}</h1></div><button className="status" onClick={async()=>{await request('api/auth/logout',{method:'POST'});setUsuario(null)}}>● {usuario} · Salir</button></header>{config&&<div className="toolbar">{active==='clientes'&&<><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Cédula, apellidos o nombres"/><button onClick={load}>Buscar</button></>}<button className="primary" onClick={()=>setEditing(null)}>+ Nuevo</button></div>}{editing!==undefined&&config&&<Editor config={config} initial={editing} onCancel={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load()}}/>}{error?<section className="empty"><h2>No se pudo completar la operación</h2><p>{error}</p></section>:active==='resumen'?<Dashboard data={data}/>:<Table data={data} editable={!!config} onEdit={setEditing} onDelete={remove}/>}</main></div>}
function Editor({config,initial,onCancel,onSaved}:{config:Config;initial:Row|null;onCancel:()=>void;onSaved:()=>void}){const[form,setForm]=useState<Row>(initial??{}),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const editing=!!initial,id=initial?.[config.id];const body=Object.fromEntries(config.fields.map(f=>[f.name,f.type==='number'?Number(form[f.name]??0):String(form[f.name]??'')]));if(editing&&config.id==='cedula')body.cedula=initial?.cedula;if(editing&&config.id==='ciRuc')body.ciRuc=initial?.ciRuc;const r=await fetch(`${api}/${config.base}${editing?`/${encodeURIComponent(String(id))}`:''}`,{method:editing?'PUT':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const p=await r.json().catch(()=>null);throw new Error(p?.title??`Error ${r.status}`)}onSaved()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}}return <section className="panel editor"><h2>{initial?'Editar registro':'Nuevo registro'}</h2><form onSubmit={submit}><div className="form-grid">{config.fields.map(f=><label key={f.name}>{f.label}<input type={f.type??'text'} step={f.type==='number'?'any':undefined} required={f.required} disabled={!!initial&&f.name===config.id} value={String(form[f.name]??'')} onChange={e=>setForm({...form,[f.name]:e.target.value})}/></label>)}</div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form></section>}
function Login({onLogin}:{onLogin:(u:string)=>void}){const[u,setU]=useState(''),[p,setP]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${api}/api/auth/login`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuario:u,clave:p}),signal:AbortSignal.timeout(10000)});if(!r.ok){setError(r.status===401?'Usuario o contraseña incorrectos':`La API respondió con error ${r.status}`);return}onLogin((await r.json()).usuario)}catch(e){setError(e instanceof DOMException&&e.name==='TimeoutError'?'La aplicación no respondió a tiempo. Verifique que el servidor esté iniciado.':'No se pudo conectar con el servidor de la aplicación.')}finally{setBusy(false)}}return <div className="shell"><main><section className="panel login"><p className="eyebrow">SISTEMA COMERCIAL</p><h1>Iniciar sesión</h1><form onSubmit={submit} className="login-form"><input required disabled={busy} value={u} onChange={e=>setU(e.target.value)} placeholder="Usuario"/><input required disabled={busy} type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Contraseña"/><button className="primary" disabled={busy}>{busy?'Conectando…':'Ingresar'}</button>{error&&<p className="form-error">{error}</p>}</form></section></main></div>}
function Dashboard({data}:{data:unknown}){const d=(data??{})as Record<string,number>;return <div className="cards">{[['Clientes',d.clientes],['Productos',d.productos],['Instalaciones',d.instalaciones],['Mensualidades pendientes',d.mensualidadesPendientes]].map(([x,n])=><article key={String(x)}><small>{x}</small><strong>{n??'—'}</strong></article>)}</div>}
function Table({data,editable,onEdit,onDelete}:{data:unknown;editable:boolean;onEdit:(r:Row)=>void;onDelete:(r:Row)=>void}){
 const rows=Array.isArray(data)?data as Row[]:[];
 if(rows[0]&&'generaMensual'in rows[0])return <MonthlyGenerator/>;
 if(rows[0]&&'fechaPago'in rows[0])return <PaymentsView initial={rows as unknown as Parameters<typeof PaymentsView>[0]['initial']}/>;
 const kind=rows[0]&&'proveedor'in rows[0]?'compras':rows[0]&&'cliente'in rows[0]&&'tipo'in rows[0]?'facturas':null;
 if(kind==='facturas')return <DocumentForm kind="facturas"/>;
 if(!rows.length)return <section className="empty"><h2>Sin registros</h2></section>;
 const hasActions=editable,keys=Object.keys(rows[0]).filter(x=>typeof rows[0][x]!=='object').slice(0,9),columns=[...keys.map(key=>({data:key,title:label(key)})),...(hasActions?[{data:null,name:'acciones',title:'Acciones',orderable:false,searchable:false}]:[])];
 const slots=hasActions?{acciones:(_value:unknown,row:Row)=><div className="row-actions"><button onClick={()=>onEdit(row)}>Editar</button><button onClick={()=>onDelete(row)}>Anular</button></div>}:undefined;
 return <>{kind&&<DocumentForm kind={kind}/>}<section className="panel table"><DataTable key={keys.join('|')+(hasActions?'|acciones':'')} data={rows} columns={columns} className="display compact" options={{destroy:true,pageLength:10,lengthMenu:[5,10,25,50],order:[],language:{search:'Buscar:',lengthMenu:'Mostrar _MENU_ registros',info:'Mostrando _START_ a _END_ de _TOTAL_',infoEmpty:'Sin registros',zeroRecords:'No se encontraron coincidencias',paginate:{first:'Primera',last:'Última',next:'Siguiente',previous:'Anterior'}}}} slots={slots}><thead><tr>{columns.map((c,i)=><th key={i}>{c.title}</th>)}</tr></thead></DataTable></section></>
}
function label(value:string){return value.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
function Center({text}:{text:string}){return <div className="shell"><main><section className="empty"><h2>{text}</h2></section></main></div>}
