import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import './DocumentForm.css';
import './ClientSearch.css';
import './InvoiceActions.css';

type Kind='facturas'|'compras';
type Product={codigo:number;descripcion:string;precio:number};
type Detail={productoCodigo:number;cantidad:number;precio:number};
type Party={nombre:string;direccion:string;telefono:string;email:string};
type ClientMatch={cedula:string;nombres:string;apellidos:string;direccion:string;telefono?:string;email?:string};
type Monthly={codigo:number;instalacionCodigo:number;desde:string;hasta:string;cuota:number};
type Invoice={numero:number;tipo:string;fecha:string;subtotal:number;descuento:number;impuesto:number;total:number;estado:string};
const api=import.meta.env.VITE_API_URL??'';

export default function DocumentForm({kind}:{kind:Kind}){
 const[open,setOpen]=useState(false),[products,setProducts]=useState<Product[]>([]),[details,setDetails]=useState<Detail[]>([{productoCodigo:0,cantidad:1,precio:0}]);
 const[identification,setIdentification]=useState(''),[party,setParty]=useState<Party|null>(null),[matches,setMatches]=useState<ClientMatch[]>([]);
 const[monthlies,setMonthlies]=useState<Monthly[]>([]),[selectedMonthlies,setSelectedMonthlies]=useState<number[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[number,setNumber]=useState<number|null>(null);
 const[date,setDate]=useState(new Date().toISOString().slice(0,10)),[discount,setDiscount]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[looking,setLooking]=useState(false);

 useEffect(()=>{if(!open)return;fetch(`${api}/api/documentos/siguiente-numero/${kind}`,{credentials:'include'}).then(r=>r.json()).then(n=>setNumber(n.numero));if(kind==='compras')fetch(`${api}/api/modulos/productos`,{credentials:'include'}).then(r=>r.json()).then(setProducts)},[open,kind]);
 const chosen=monthlies.filter(x=>selectedMonthlies.includes(x.codigo));
 const grossMonthly=chosen.reduce((s,x)=>s+Number(x.cuota),0);
 const subtotal=kind==='facturas'?grossMonthly/1.15:details.reduce((s,x)=>s+x.cantidad*x.precio,0);
 const tax=kind==='facturas'?Math.max(0,grossMonthly-discount)/1.15*.15:Math.max(0,subtotal-discount)*.15,total=kind==='facturas'?Math.max(0,grossMonthly-discount):subtotal-discount+tax;
 const valid=!!party&&(kind==='facturas'?selectedMonthlies.length>0:details.every(x=>x.productoCodigo>0&&x.cantidad>0&&x.precio>=0));

 async function chooseClient(x:ClientMatch){
  const fullName=`${x.nombres} ${x.apellidos}`.toUpperCase();const special=fullName.includes('JUAN')&&fullName.includes('CARLOS')&&fullName.includes('QUITO')&&fullName.includes('RIVERA');
  setIdentification(x.cedula);setParty({nombre:`${x.nombres} ${x.apellidos}`,direccion:x.direccion,telefono:x.telefono??'',email:x.email??''});setDiscount(special?5:0);setMatches([]);setMessage('');setSelectedMonthlies([]);
  const [monthlyResponse,invoiceResponse]=await Promise.all([fetch(`${api}/api/documentos/clientes/${encodeURIComponent(x.cedula)}/mensualidades-pendientes`,{credentials:'include'}),fetch(`${api}/api/documentos/clientes/${encodeURIComponent(x.cedula)}/facturas`,{credentials:'include'})]);const rows:Monthly[]=monthlyResponse.ok?await monthlyResponse.json():[];setMonthlies(rows);setInvoices(invoiceResponse.ok?await invoiceResponse.json():[]);if(!rows.length)setMessage('Este cliente no tiene mensualidades pendientes.');
 }
 async function findParty(){
  const term=identification.trim();setLooking(true);setParty(null);setMatches([]);setMonthlies([]);setSelectedMonthlies([]);setMessage('');
  try{if(kind==='facturas'){const r=await fetch(`${api}/api/clientes?buscar=${encodeURIComponent(term)}`,{credentials:'include'});if(!r.ok)throw new Error('No se pudo consultar clientes.');const rows:ClientMatch[]=await r.json();if(!rows.length)throw new Error('No se encontraron clientes activos.');if(rows.length===1){await chooseClient(rows[0]);return}setMatches(rows);setMessage(`Se encontraron ${rows.length} coincidencias. Seleccione un cliente.`);return}const r=await fetch(`${api}/api/administracion/proveedores/${encodeURIComponent(term)}`,{credentials:'include'});if(!r.ok)throw new Error('Proveedor no encontrado o anulado.');const x=await r.json();setParty({nombre:x.razonSocial,direccion:x.direccion,telefono:x.telefono??x.celular??'',email:x.email??''})}catch(e){setMessage(e instanceof Error?e.message:'No se pudo consultar')}finally{setLooking(false)}
 }
 function change(i:number,key:keyof Detail,value:number){setDetails(rows=>rows.map((x,n)=>n===i?{...x,[key]:value}:x))}
 function selectProduct(i:number,codigo:number){const p=products.find(x=>x.codigo===codigo);setDetails(rows=>rows.map((x,n)=>n===i?{...x,productoCodigo:codigo,precio:p?.precio??0}:x))}
 async function annulInvoice(numero:number){if(!confirm(`¿Desea anular la factura ${numero}? Las mensualidades quedarán disponibles para refacturar.`))return;setBusy(true);setMessage('');try{const r=await fetch(`${api}/api/documentos/facturas/${numero}/anular`,{method:'POST',credentials:'include'}),body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.title??`Error ${r.status}`);setMessage(body.mensaje);const [monthlyResponse,invoiceResponse]=await Promise.all([fetch(`${api}/api/documentos/clientes/${encodeURIComponent(identification)}/mensualidades-pendientes`,{credentials:'include'}),fetch(`${api}/api/documentos/clientes/${encodeURIComponent(identification)}/facturas`,{credentials:'include'})]);setMonthlies(monthlyResponse.ok?await monthlyResponse.json():[]);setInvoices(invoiceResponse.ok?await invoiceResponse.json():[]);setSelectedMonthlies([])}catch(e){setMessage(e instanceof Error?e.message:'No se pudo anular la factura')}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();if(!valid){setMessage(kind==='facturas'?'Seleccione al menos una mensualidad pendiente.':'Busque un proveedor válido y seleccione productos.');return}setBusy(true);setMessage('');try{const body=kind==='facturas'?{tipo:'FA',clienteCedula:identification,fecha:date,descuento:discount,detalles:[],mensualidadCodigos:selectedMonthlies}:{tipo:1,proveedorCiRuc:identification,fecha:date,descuento:discount,detalles:details};const r=await fetch(`${api}/api/documentos/${kind}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),response=await r.json().catch(()=>null);if(!r.ok)throw new Error(response?.title??`Error ${r.status}`);setNumber(response.numero);setMessage(`${kind==='facturas'?'Factura':'Compra'} número ${response.numero} guardada correctamente.`);setDetails([{productoCodigo:0,cantidad:1,precio:0}]);setDiscount(0);setMonthlies([]);setSelectedMonthlies([])}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}}
 if(!open)return <button className="primary document-new" onClick={()=>setOpen(true)}>+ Nueva {kind==='facturas'?'factura':'compra'}</button>;
 return <><section className="panel document-form"><div className="document-title"><div><p className="eyebrow">{kind==='facturas'?'FACTURA':'COMPROBANTE DE COMPRA'}</p><h2>N.º {number??'—'} · {kind==='facturas'?'FA':'COMPRA'}</h2></div><button onClick={()=>setOpen(false)}>Cerrar</button></div><form onSubmit={submit}>
  <h3>Datos del {kind==='facturas'?'cliente':'proveedor'}</h3><div className="party-search"><label>{kind==='facturas'?'Cédula/RUC, nombres o apellidos':'Cédula/RUC'}<input required value={identification} onChange={e=>{setIdentification(e.target.value);setParty(null);setMatches([]);setMonthlies([]);setSelectedMonthlies([]);setInvoices([])}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();findParty()}}}/></label><button type="button" onClick={findParty} disabled={looking||identification.trim().length<2}>{looking?'Buscando…':'Buscar'}</button></div>
  {matches.length>0&&<div className="client-results">{matches.map(x=><button type="button" key={x.cedula} onClick={()=>chooseClient(x)}><strong>{x.apellidos} {x.nombres}</strong><span>{x.cedula} · {x.direccion}</span></button>)}</div>}
  <div className="party-card"><label>Nombre / razón social<input readOnly value={party?.nombre??''}/></label><label>Dirección<input readOnly value={party?.direccion??''}/></label><label>Teléfono<input readOnly value={party?.telefono??''}/></label><label>Correo<input readOnly value={party?.email??''}/></label></div><div className="form-grid"><label>Fecha<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Estado<input readOnly value="ACTIVO"/></label><label>Descuento<input min="0" step="0.01" type="number" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label></div>
  <h3>{kind==='facturas'?'Mensualidades pendientes':'Detalle'}</h3>
  {kind==='facturas'?<div className="monthly-list">{monthlies.map(m=><label key={m.codigo}><input type="checkbox" checked={selectedMonthlies.includes(m.codigo)} onChange={e=>setSelectedMonthlies(x=>e.target.checked?[...x,m.codigo]:x.filter(id=>id!==m.codigo))}/><span><strong>Instalación {m.instalacionCodigo}</strong><small>{m.desde} a {m.hasta}</small></span><b>${Number(m.cuota).toFixed(2)}</b></label>)}</div>:<><div className="detail-head"><span>Producto</span><span>Cantidad</span><span>Precio</span><span>Total</span><span></span></div><div className="detail-lines">{details.map((d,i)=><div className="detail-row" key={i}><select required value={d.productoCodigo} onChange={e=>selectProduct(i,Number(e.target.value))}><option value="0">Seleccione producto</option>{products.map(p=><option key={p.codigo} value={p.codigo}>{p.codigo} · {p.descripcion}</option>)}</select><input required min="0.0001" step="0.0001" type="number" value={d.cantidad} onChange={e=>change(i,'cantidad',Number(e.target.value))}/><input required min="0" step="0.0001" type="number" value={d.precio} onChange={e=>change(i,'precio',Number(e.target.value))}/><strong>{(d.cantidad*d.precio).toFixed(2)}</strong><button type="button" disabled={details.length===1} onClick={()=>setDetails(x=>x.filter((_,n)=>n!==i))}>Quitar</button></div>)}</div><button type="button" onClick={()=>setDetails(x=>[...x,{productoCodigo:0,cantidad:1,precio:0}])}>+ Agregar producto</button></>}
  <div className="totals"><span>Subtotal <b>{subtotal.toFixed(2)}</b></span><span>Descuento <b>{discount.toFixed(2)}</b></span><span>IVA 15 % <b>{tax.toFixed(2)}</b></span><span>Total <b>{total.toFixed(2)}</b></span></div>{message&&<p className={matches.length?'form-info':message.includes('correctamente')?'form-success':'form-error'}>{message}</p>}<div className="actions"><button className="primary" disabled={busy||!valid}>{busy?'Guardando…':'Guardar documento'}</button></div>
 </form></section>{kind==='facturas'&&<section className="panel monthly-history"><h2>Facturas del cliente</h2>{!party?<p>Seleccione un cliente para visualizar sus facturas.</p>:!invoices.length?<p>El cliente todavía no tiene facturas.</p>:<div className="history-scroll"><table><thead><tr><th>Número</th><th>Tipo</th><th>Fecha</th><th>Subtotal</th><th>IVA</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{invoices.map(x=><tr key={x.numero}><td>{x.numero}</td><td>{x.tipo}</td><td>{new Date(x.fecha).toLocaleDateString('es-EC')}</td><td>${Number(x.subtotal).toFixed(2)}</td><td>${Number(x.impuesto).toFixed(2)}</td><td>${Number(x.total).toFixed(2)}</td><td>{x.estado}</td><td><div className="invoice-actions"><button type="button" onClick={()=>window.open(`${api}/api/documentos/facturas/${x.numero}/imprimir`,'_blank')}>Imprimir</button><button type="button" className="danger" disabled={x.estado==='ANU'||busy} onClick={()=>annulInvoice(x.numero)}>Anular</button></div></td></tr>)}</tbody></table></div>}</section>}</>
}
