import {useState} from 'react';
import type {FormEvent} from 'react';
import './MonthlyGenerator.css';
type Client={cedula:string;nombres:string;apellidos:string;direccion:string};
type Monthly={codigo:number;instalacionCodigo:number;clienteCedula:string;desde:string;hasta:string;cuota:number;factura?:number;estado:string};
type Preview={instalacionCodigo:number;desde:string;hasta:string;cuota:number};
const api=import.meta.env.VITE_API_URL??'';
export default function MonthlyGenerator(){
 const[term,setTerm]=useState(''),[matches,setMatches]=useState<Client[]>([]),[client,setClient]=useState<Client|null>(null),[rows,setRows]=useState<Monthly[]>([]),[preview,setPreview]=useState<Preview[]>([]);
 const[until,setUntil]=useState(new Date().toISOString().slice(0,10)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function search(){setMessage('');setClient(null);setRows([]);setPreview([]);if(term.trim().length<2)return;const r=await fetch(`${api}/api/clientes?buscar=${encodeURIComponent(term.trim())}`,{credentials:'include'}),data:Client[]=r.ok?await r.json():[];setMatches(data);if(!data.length)setMessage('No se encontraron clientes activos.')}
 async function history(cedula:string){const r=await fetch(`${api}/api/servicios/clientes/${encodeURIComponent(cedula)}/mensualidades`,{credentials:'include'});setRows(r.ok?await r.json():[])}
 async function choose(x:Client){setClient(x);setTerm(x.cedula);setMatches([]);setPreview([]);setMessage('');await history(x.cedula)}
 async function review(e:FormEvent){e.preventDefault();if(!client)return;setBusy(true);setPreview([]);setMessage('');try{const r=await fetch(`${api}/api/servicios/mensualidades/previsualizar`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({clienteCedula:client.cedula,hasta:until})}),body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.title??`Error ${r.status}`);setPreview(body.mensualidades??[]);setMessage(body.mensaje)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo calcular la vista previa')}finally{setBusy(false)}}
 async function create(){if(!client||!preview.length||!confirm(`¿Confirma la creación de ${preview.length} mensualidades?`))return;setBusy(true);setMessage('');try{const r=await fetch(`${api}/api/servicios/mensualidades/generar`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({clienteCedula:client.cedula,hasta:until})}),body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.title??`Error ${r.status}`);setMessage(body.mensaje);setPreview([]);await history(client.cedula)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo generar')}finally{setBusy(false)}}
 async function undoToday(){if(!client||!confirm('¿Desea eliminar las mensualidades generadas de más hoy? Se conservará el período más reciente de cada instalación activa con cuota.'))return;setBusy(true);setMessage('');try{const r=await fetch(`${api}/api/servicios/mensualidades/deshacer-generacion-hoy`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({clienteCedula:client.cedula})}),body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.title??`Error ${r.status}`);setMessage(body.mensaje);setPreview([]);await history(client.cedula)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo deshacer la generación')}finally{setBusy(false)}}
 return <><section className="panel monthly-generator"><h2>Genera mensual</h2><form onSubmit={review}><div className="generator-grid"><label>Buscar por cédula, nombres o apellidos<input value={term} onChange={e=>{setTerm(e.target.value);setClient(null);setRows([]);setMatches([]);setPreview([])}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();search()}}}/></label><button type="button" onClick={search} disabled={term.trim().length<2}>Buscar</button><label>Generar hasta<input type="date" required value={until} onChange={e=>{setUntil(e.target.value);setPreview([])}}/></label></div>{matches.length>0&&<div className="client-results">{matches.map(x=><button type="button" key={x.cedula} onClick={()=>choose(x)}><strong>{x.apellidos} {x.nombres}</strong><span>{x.cedula} · {x.direccion}</span></button>)}</div>}<label className="selected-client">Nombre del cliente<input readOnly value={client?`${client.apellidos} ${client.nombres}`:''}/></label>{message&&<p className="form-info">{message}</p>}<div className="actions"><button type="button" className="danger" disabled={!client||busy} onClick={undoToday}>Deshacer generación de hoy</button><button className="primary" disabled={!client||busy}>{busy?'Calculando…':'Revisar mensualidades'}</button></div></form></section>
 {preview.length>0&&<section className="panel preview-monthlies"><h2>Mensualidades que se crearán</h2><p>Revise cuidadosamente. Todavía no se ha guardado ningún registro.</p><div className="history-scroll"><table><thead><tr><th>Instalación</th><th>Desde</th><th>Hasta</th><th>Cuota</th></tr></thead><tbody>{preview.map(x=><tr key={`${x.instalacionCodigo}-${x.desde}`}><td>{x.instalacionCodigo}</td><td>{x.desde}</td><td>{x.hasta}</td><td>${Number(x.cuota).toFixed(2)}</td></tr>)}</tbody></table></div><div className="actions"><button type="button" onClick={()=>setPreview([])}>Cancelar</button><button type="button" className="primary" disabled={busy} onClick={create}>{busy?'Creando…':`Crear ${preview.length} mensualidades`}</button></div></section>}
 <section className="panel monthly-history"><h2>Historial del cliente</h2>{!client?<p>Seleccione un cliente para visualizar su historial.</p>:!rows.length?<p>El cliente todavía no tiene mensualidades.</p>:<div className="history-scroll"><table><thead><tr><th>Código</th><th>Instalación</th><th>Desde</th><th>Hasta</th><th>Cuota</th><th>Factura</th><th>Estado</th></tr></thead><tbody>{rows.map(x=><tr key={x.codigo}><td>{x.codigo}</td><td>{x.instalacionCodigo}</td><td>{x.desde}</td><td>{x.hasta}</td><td>${Number(x.cuota).toFixed(2)}</td><td>{x.factura??'—'}</td><td>{x.estado}</td></tr>)}</tbody></table></div>}</section></>
}
