import {useState} from 'react';
import DataTable from 'datatables.net-react';
import DT from 'datatables.net-dt';
import './PaymentsView.css';
// oxlint-disable-next-line react-hooks/rules-of-hooks -- DataTables plugin registration, not a React Hook.
DataTable.use(DT);
type Payment={fechaPago:string;factura:number;cedula:string;cliente:string;subtotal?:number;descuento?:number;impuesto?:number;total:number;estado:string;mensualidades:number};
const api=import.meta.env.VITE_API_URL??'';
export default function PaymentsView({initial}:{initial:Payment[]}){const[rows,setRows]=useState(initial),[cedula,setCedula]=useState(''),[desde,setDesde]=useState(''),[hasta,setHasta]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function search(){setBusy(true);setError('');try{const q=new URLSearchParams();if(cedula)q.set('cedula',cedula);if(desde)q.set('desde',desde);if(hasta)q.set('hasta',hasta);const r=await fetch(`${api}/api/consultas/pagos?${q}`,{credentials:'include'});if(!r.ok)throw new Error(`Error ${r.status}`);setRows(await r.json())}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar')}finally{setBusy(false)}}const columns=[{data:'fechaPago',title:'Fecha de pago',render:(v:string)=>new Date(v).toLocaleString('es-EC')},{data:'factura',title:'Factura'},{data:'cedula',title:'Cédula/RUC'},{data:'cliente',title:'Cliente'},{data:'total',title:'Total',render:(v:number)=>Number(v).toFixed(2)},{data:'estado',title:'Estado'},{data:'mensualidades',title:'Mensualidades'},{data:null,name:'acciones',title:'Acciones',orderable:false,searchable:false}];return <><section className="panel payment-filters"><h2>Consulta de pagos registrados</h2><p>La fecha corresponde a la factura vinculada en la base.</p><div className="filter-grid"><label>Cédula/RUC<input value={cedula} onChange={e=>setCedula(e.target.value)} placeholder="Todos"/></label><label>Desde<input type="date" value={desde} onChange={e=>setDesde(e.target.value)}/></label><label>Hasta<input type="date" value={hasta} onChange={e=>setHasta(e.target.value)}/></label><button className="primary" onClick={search} disabled={busy}>{busy?'Consultando…':'Consultar'}</button></div>{error&&<p className="form-error">{error}</p>}</section><section className="panel table"><DataTable key={`${rows.length}-${cedula}-${desde}-${hasta}`} data={rows} columns={columns} className="display compact" options={{pageLength:10,order:[[0,'desc']],language:{search:'Buscar en resultados:',lengthMenu:'Mostrar _MENU_',info:'Mostrando _START_ a _END_ de _TOTAL_',zeroRecords:'Sin coincidencias',paginate:{next:'Siguiente',previous:'Anterior'}}}} slots={{acciones:(_v:unknown,row:Payment)=><button onClick={()=>window.open(`${api}/api/documentos/facturas/${row.factura}/imprimir`,'_blank')}>Imprimir</button>}}><thead><tr>{columns.map((x,i)=><th key={i}>{x.title}</th>)}</tr></thead></DataTable></section></>}
